version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    container_name: databse_mysql
    environment:
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "formulario"
    ports:
      - "3306:3306"
    volumes:
      - /home/demilson/documents/Docker/Volumes/MySql:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    container_name: sgbd_web
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge